### ISSUE TITLE
Switch V2 support?

### ISSUE THREAD

**Issue by vbaros** [fabaff/python-mystrom#4]
New switches with temp sensors are released. The API has a new temperature API. Can you please support it with the lib and in home assistant?

Here is the link:
https://mobile.twitter.com/myStrom_AG/status/944152156021710850

I have the new switch and the temp is properly returned from the switch using the new API command.

**Comment by messismore** [comment]
I have a V2. `[ip]/temp` returns:

```
{
	"measured":	46.562500,
	"compensation":	21.000191,
	"compensated":	25.562309
}
```

**Comment by fabaff** [comment]
Add with https://github.com/fabaff/python-mystrom/pull/12
